MISUV-4891: SCP025 | Add SE | Build - Add business start date page and Add business start date check page
hmrc/income-tax-view-change-frontend pull request #1727
Opened 2023-05-25 01:17 UTC by ayubAz

2023-05-26 07:33 UTC, avelx commented on app/controllers/AddBusinessStartDateController.scala
> +  def show(): Action[AnyContent] = (checkSessionTimeout andThen authenticate andThen retrieveNino
duplicated code in function definition

2023-05-26 07:39 UTC, avelx commented on app/controllers/AddBusinessStartDateController.scala
> +          Logger("application").error(s"${if (isAgent) "[Agent]"}" +
I am not sure if this would be evaluated correctly;

2023-05-26 07:39 UTC, avelx commented on app/controllers/AddBusinessStartDateController.scala
> +import auth.MtdItUser
pls remove not used imports

2023-05-26 07:59 UTC, avelx commented on app/forms/incomeSources/add/BusinessStartDateForm.scala
> +object BusinessStartDateForm {
you are using mixing approach here: passing implict in apply method and passing these as params to instantiate object for DI ; 
there is really no need to use DI like other devs are doing, please avoid this;
here is example how you can do this:
https://github.com/hmrc/income-tax-view-change-frontend/compare/MISUV-4891-1_fix?expand=1

2023-05-26 08:04 UTC, avelx commented on app/views/components/dateInput.scala.html
> +        labelClass: Option[String] = None,
not sure if UI wise there will be ever situation when labelClass will be None? maybe not worth to model this field like Optional?

2023-05-26 08:22 UTC, avelx requested changes
please address comments

2023-05-26 16:05 UTC, edward-dennis-ey commented on app/forms/incomeSources/add/BusinessStartDateForm.scala
> +  override protected def maxDate(maximum: LocalDate, errorKey: String, args: Any*): Constraint[LocalDate] =
Not sure why this has been overridden?

2023-05-26 16:06 UTC, edward-dennis-ey commented on app/forms/incomeSources/add/BusinessStartDateForm.scala
> +  override protected def maxDate(maximum: LocalDate, errorKey: String, args: Any*): Constraint[LocalDate] =
The requirements are to stop entry above 7 days, so it should be after (not equals) as per my implementation of this function

2023-05-30 08:50 UTC, avelx commented on app/controllers/AddBusinessStartDateController.scala
> +              .addingToSession(SessionKeys.businessStartDate -> formData.date.toString)
I don't see any immediate issues related to the format we store date, but just to note that this is a sensitive part

2023-05-30 09:05 UTC, avelx commented on app/forms/incomeSources/add/BusinessStartDateForm.scala
> +        date => (date.getDayOfMonth.toString, date.getMonthValue.toString, date.getYear.toString)
this would be easy to store these as Int, but lets leave these for next iteration / refactoring

2023-05-30 09:06 UTC, avelx approved these changes
approved

2023-05-31 12:38 UTC, avelx commented on app/controllers/AddBusinessStartDateCheckController.scala
> +    Future.successful(
Please wrap only Redirect part with Future.success;
On line 126 you should use actual Future instead

2023-05-31 12:47 UTC, avelx commented on app/forms/BusinessStartDateCheckForm.scala
> +  val csrfToken: String = "csrfToken"
I dont really think we need this value => as this is something to be supported by the framework; but worth to confirm
`
val csrfToken: String = "csrfToken"
`

2023-05-31 13:03 UTC, avelx commented on conf/messages
> +dateForm.hint                                                       = For example, 27 3 2020
I don't think this is the only one form have date input, so you need to have more details in the prefix i.e
> addbusinessstartdateform.hint ?

2023-06-01 07:32 UTC, avelx commented on app/controllers/incomeSources/add/AddIncomeSourceController.scala
> +      incomeSourceDetailsService.getAddIncomeSourceViewModel(sources) match {
would be easier to wrap this whole expression with Future, but I guess we can leave things as is

2023-06-01 07:43 UTC, avelx approved these changes
approved

2023-06-01 08:14 UTC, merged