MISUV-7470: Error page - submission validation
hmrc/income-tax-view-change-frontend pull request #2348
Opened 2024-06-14 08:59 UTC by james-king-hmrc

Error page - submission validation

2024-06-17 08:53 UTC, tharunprasath requested changes

2024-06-17 08:53 UTC, tharunprasath commented on app/controllers/optOut/OptOutErrorController.scala
OptOutErrorController UTs and ITs need to be added.

2024-06-17 08:54 UTC, tharunprasath commented on app/views/optOut/OptOutError.scala.html
Do we agree not to use HTML tags?

2024-06-17 08:58 UTC, james-king-hmrc commented on app/views/optOut/OptOutError.scala.html
yes for pages using forms to be submitted, do you think we need Nunjucks here?

2024-06-17 08:58 UTC, tharunprasath commented on app/views/optOut/OptOutError.scala.html
Reuse ErrorTemplate.scala.html & ErrorTemplateWithLink.scala.html

2024-06-17 10:10 UTC, james-king-hmrc commented on app/controllers/optOut/OptOutErrorController.scala
done

2024-06-17 10:36 UTC, james-king-hmrc commented on app/views/optOut/OptOutError.scala.html
not sure they support the the format we need here

2024-06-18 06:17 UTC, tharunprasath commented on app/controllers/optOut/OptOutErrorController.scala
We could add the logger to print the reasons for API failure. All the API failures are generalised under OptOutUpdateResponseFailure.defaultFailure. We could add the possible test data for the listed failure codes in our test as error scenarios won't be covered in ATs.

2024-06-18 13:33 UTC, james-king-hmrc commented on app/views/optOut/OptOutError.scala.html
done

2024-06-18 13:45 UTC, james-king-hmrc commented on app/controllers/optOut/OptOutErrorController.scala
not sure I understand this comment, let's chat when you're free to calrify

2024-06-18 14:54 UTC, SiddharthAtos approved these changes

2024-06-18 15:26 UTC, james-king-hmrc commented on app/controllers/optOut/OptOutErrorController.scala
this comment has been addressed and apporved, please reslove

2024-06-18 15:27 UTC, james-king-hmrc commented on app/views/optOut/OptOutError.scala.html
this comment has been addressed and apporved, please reslove

2024-06-18 15:35 UTC, SiddharthAtos commented on it/test/controllers/optOut/ConfirmOptOutControllerISpec.scala
> +          httpStatus(SEE_OTHER)
should fix: redirectURI should be verified  with SEE_OTHER status

2024-06-18 16:03 UTC, merged