DO NOT MERGE - Created method to check for main transaction codes and retrieve…
hmrc/income-tax-view-change-frontend pull request #2528
Opened 2024-09-23 11:20 UTC by tioadesola1

… documentdetails.

DO NOT MERGE

2024-09-25 13:38 UTC, tharunprasath requested changes

2024-09-25 13:38 UTC, tharunprasath commented on app/connectors/IncomeTaxCalculationConnector.scala
> +              Logger("application").error(s"AAAAAAAAAAAAAAAAAAAAA Response: $valid\n")
Could you please add a valid logger?

2024-09-25 13:38 UTC, tharunprasath commented on app/controllers/TaxDueSummaryController.scala
> +
Could be made unchanged

2024-09-25 13:38 UTC, tharunprasath commented on app/views/TaxCalcBreakdown.scala.html
> +            if(scottishRegime && (band.name == "ART" || band.name == "AVRT" && taxYear >= 2024)) {
Would this be more readable like "if (scottishRegime && (band.name == "ART" || (band.name == "AVRT" && taxYear >= 2024)))". Also, can the magic number be removed with a valid name to understand the criteria like MIN_YEAR_FOR_SCOTTISH_REGIME or a better one?

2024-09-25 13:38 UTC, tharunprasath commented on conf/messages
> +taxCal_breakdown.table.AVRT_scottish                                = Advanced rate ({0} at {1}%)
Do we need to handle Welsh?

2024-09-25 13:38 UTC, tharunprasath commented on test/testConstants/NewCalcBreakdownUnitTestConstants.scala
> +      TaxBands(
Good to see the test for this AC "Please adhere to existing sorting method
@for(band <- viewModel.lumpSumsBands.getOrElse(Seq()).filter(.income > 0).sortBy(.rate)) { @taxBandTableRow(band, viewModel.taxRegime.contains("Scotland")) }" in both Pay, pensions and profit and Employment lump sums

2024-09-26 15:12 UTC, tharunprasath approved these changes

2024-09-30 10:01 UTC, vinay1yv approved these changes

2024-09-30 10:04 UTC, merged