Misuv 8738
hmrc/income-tax-view-change-frontend pull request #2653
Opened 2024-11-22 13:47 UTC by WozCapGem

2024-11-22 14:25 UTC, Chrissystk requested changes
Have the ATs run and passed?

2024-11-22 14:25 UTC, Chrissystk commented on test/views/incomeSources/manage/ManageIncomeSourceDetailsViewSpec.scala
> +        .show(taxYear, changeTo, incomeSourceType = SelfEmployment).url
Again this should be an if statement

2024-11-22 14:25 UTC, Chrissystk commented on test/views/incomeSources/manage/ManageIncomeSourceDetailsViewSpec.scala
> +      controllers.incomeSources.manage.routes.ConfirmReportingMethodSharedController.show(taxYear, changeTo, UkProperty).url
Again this should be an if statement

2024-11-22 14:25 UTC, Chrissystk commented on test/views/incomeSources/manage/ManageIncomeSourceDetailsViewSpec.scala
> +      controllers.incomeSources.manage.routes.ConfirmReportingMethodSharedController.show(taxYear, changeTo, ForeignProperty).url
Again this should be an if statement

2024-11-22 14:25 UTC, Chrissystk commented on test/views/incomeSources/manage/ManageIncomeSourceDetailsViewSpec.scala
> +      controllers.incomeSources.manage.routes.ConfirmReportingMethodSharedController.show(taxYear, changeTo, ForeignProperty).url
Again this should be an if statement

2024-11-22 14:25 UTC, Chrissystk commented on test/views/manageBusinesses/manage/ManageIncomeSourceDetailsViewSpec.scala
> +        .show(taxYear, changeTo, incomeSourceType = SelfEmployment).url
Again this should be an if statement

2024-11-22 14:25 UTC, Chrissystk commented on test/views/manageBusinesses/manage/ManageIncomeSourceDetailsViewSpec.scala
> +        .show(taxYear, changeTo, incomeSourceType = SelfEmployment).url
Again this should be an if statement

2024-11-22 14:25 UTC, Chrissystk commented on test/views/manageBusinesses/manage/ManageIncomeSourceDetailsViewSpec.scala
> +      controllers.manageBusinesses.manage.routes.ConfirmReportingMethodSharedController.show(taxYear, changeTo,UkProperty).url
Again this should be an if statement

2024-11-22 14:25 UTC, Chrissystk commented on test/views/manageBusinesses/manage/ManageIncomeSourceDetailsViewSpec.scala
> +        .show(taxYear, changeTo, incomeSourceType = SelfEmployment).url
Again this should be an if statement

2024-11-22 14:25 UTC, Chrissystk commented on test/views/manageBusinesses/manage/ManageIncomeSourceDetailsViewSpec.scala
> +        .show(taxYear, changeTo, incomeSourceType = SelfEmployment).url
Again this should be an if statement

2024-11-22 14:25 UTC, Chrissystk commented on test/views/manageBusinesses/manage/ManageIncomeSourceDetailsViewSpec.scala
> +      controllers.manageBusinesses.manage.routes.ConfirmReportingMethodSharedController.show(taxYear, changeTo, ForeignProperty).url
Again this should be an if statement

2024-11-22 14:25 UTC, Chrissystk commented on test/views/manageBusinesses/manage/ManageIncomeSourceDetailsViewSpec.scala
> +      controllers.manageBusinesses.manage.routes.ConfirmReportingMethodSharedController.show(taxYear, changeTo, ForeignProperty).url
Again this should be an if statement

2024-11-22 14:25 UTC, Chrissystk commented on test/views/manageBusinesses/manage/ManageIncomeSourceDetailsViewSpec.scala
> +        .show(taxYear, changeTo, incomeSourceType = SelfEmployment).url
Again this should be an if statement

2024-12-04 22:26 UTC, Chrissystk requested changes

2024-12-04 22:26 UTC, Chrissystk commented on app/controllers/incomeSources/manage/ConfirmReportingMethodSharedController.scala
> +      .submit(taxYear, changeTo, incomeSourceType)
This is the cause of your error. You need the submitAgent when the user is an agent.

2024-12-04 22:26 UTC, Chrissystk commented on app/controllers/manageBusinesses/manage/ConfirmReportingMethodSharedController.scala
> +              postAction = getPostAction(taxYearModel.toString, changeTo, incomeSourceType),
This is the cause of your error. You need the submitAgent when the user is an agent.

2024-12-05 12:02 UTC, WozCapGem commented
test this please

2024-12-05 20:39 UTC, Chrissystk approved these changes

2024-12-05 20:43 UTC, merged