MISUV-8823 - Migrate BtaNavBarPartialConnector to httpClientV2
hmrc/income-tax-view-change-frontend pull request #2658
Opened 2024-11-25 09:06 UTC by TomRafferty

2024-11-25 14:57 UTC, avelx commented on app/connectors/BtaNavBarPartialConnector.scala
> +  lazy val btaNavLinksUrl: URL = new URL(config.btaService + "/business-account/partial/nav-links")
_usage is deprecated => see below: 
Deprecated
Use URI. toURL() to construct an instance of URL. See the note on constructor deprecation for more details._

2024-11-26 13:20 UTC, Mbrookesy requested changes

2024-11-26 13:20 UTC, Mbrookesy commented on app/connectors/BtaNavBarPartialConnector.scala
> +import uk.gov.hmrc.http.{HeaderCarrier, HttpClient, HttpReads, HttpReadsInstances, HttpResponse}
The unused imports should be removed

2024-11-26 13:37 UTC, TomRafferty commented on app/connectors/BtaNavBarPartialConnector.scala
> +import uk.gov.hmrc.http.{HeaderCarrier, HttpClient, HttpReads, HttpReadsInstances, HttpResponse}
should be sorted now ta 😄

2024-11-26 14:04 UTC, Mbrookesy approved these changes

2024-11-26 14:36 UTC, merged