MISUV-1870 Moved agent-client relationship check to auth functionality.
hmrc/income-tax-view-change-frontend pull request #699
Opened 2021-05-13 07:24 UTC by jameshforster

2021-05-14 12:07 UTC, MihailsC-hmrc requested changes
Please align the code lines that are indented too far. Other comments are optional.

2021-05-18 07:04 UTC, jameshforster commented on app/auth/BaseFrontendController.scala
> +    protected def asyncInternal(predicate: AuthPredicate[User], requireClientSelected: Boolean = true)(action: ActionBody[User]): Action[AnyContent] =
Action is already not called unless auth passes as it requires the user to be passed in as a variable before execution

2021-05-18 07:07 UTC, jameshforster commented on app/controllers/predicates/IncomeTaxAgentUser.scala
> +	lazy val delegatedMtdEnrolments: Set[Enrolment] = enrolments.enrolments.filter(enrolment => {
Removed in later subtask

2021-05-18 07:07 UTC, jameshforster commented on app/services/agent/ClientRelationshipService.scala
> +  def checkAgentClientRelationship(utr: String, arn: String, delegatedEnrolments: Set[Enrolment])(implicit hc: HeaderCarrier): Future[Either[ClientRelationshipFailure, ClientDetails]] =
Removed in later subtask

2021-05-18 07:29 UTC, jameshforster commented on app/services/agent/ClientRelationshipService.scala
> -              case false => Left(NoAgentClientRelationship)
Removed in cleanup subtask

2021-05-18 15:51 UTC, merged