Misuv 2387 1
hmrc/income-tax-view-change-frontend pull request #872
Opened 2021-09-17 12:06 UTC by jack-malik

Implementation of changes to WhatYouOwe page incorporating frontend-hmrc.

2021-09-20 19:32 UTC, chandraAndem requested changes
Opening in new tab functionality is missing

2021-09-20 19:32 UTC, chandraAndem commented on test/views/WhatYouOweViewSpec.scala
> +//      anchor.attr("target") shouldBe "_blank"
This test should not be removed.

2021-09-20 19:32 UTC, chandraAndem commented on test/views/WhatYouOweViewSpec.scala
> +//        paymentUnderReviewParaLink.attr("target") shouldBe "_blank"
Same as above this test should not be removed as it tests openining in new tab.

2021-09-20 19:32 UTC, chandraAndem commented on test/views/WhatYouOweViewSpec.scala
> +//        paymentUnderReviewParaLink.attr("target") shouldBe "_blank"
Same as above.

2021-09-21 07:15 UTC, david-walters-HMRC commented on app/views/WhatYouOwe.scala.html
> +                            outerMessage = Some(".")).toString()), id = Some("sa-note-migrated"))
the full stop shouldn't need to String

2021-09-21 07:16 UTC, david-walters-HMRC commented on app/views/WhatYouOwe.scala.html
> +                            outerMessage = Some(".")).toString()), id = Some("sa-note-migrated"))
an id is also not needed

2021-09-21 07:23 UTC, david-walters-HMRC commented on app/views/WhatYouOwe.scala.html
> +                            <p class="govuk-body govuk-!-font-size-36 govuk-!-font-weight-bold">@chargesList.balanceDetails.overDueAmount.toCurrency</p>
p component should be being used

2021-09-21 07:24 UTC, david-walters-HMRC commented on app/views/WhatYouOwe.scala.html
> +                            <p class="govuk-body govuk-!-font-size-36 govuk-!-font-weight-bold">@chargesList.balanceDetails.balanceDueWithin30Days.toCurrency</p>
p component should be being used

2021-09-21 07:24 UTC, david-walters-HMRC commented on app/views/WhatYouOwe.scala.html
> +                            <p class="govuk-body govuk-!-font-size-36 govuk-!-font-weight-bold">@chargesList.balanceDetails.totalBalance.toCurrency</p>
p component should be being used

2021-09-21 07:25 UTC, david-walters-HMRC commented on app/views/WhatYouOwe.scala.html
>          <p>
p component should be being used

2021-09-21 07:25 UTC, david-walters-HMRC commented on app/views/WhatYouOwe.scala.html
>          <p>
p component should be being used

2021-09-21 07:27 UTC, david-walters-HMRC commented on app/views/WhatYouOwe.scala.html
> +                    <a id="payment-button-link" class="govuk-button"  role="button" href="@controllers.routes.PaymentController.paymentHandoff(chargesList.getEarliestTaxYearAndAmountByDueDate._2.toPe
should be able to use link component here

2021-09-28 10:51 UTC, closed without merging