MISUV-2436 - Created TxM Audit Event for Tax Calculation Details Response
hmrc/income-tax-view-change-frontend pull request #907
Opened 2021-10-01 12:55 UTC by Wright93

2021-10-01 17:11 UTC, MihailsC-hmrc requested changes
Some of the comments better be addressed.

2021-10-01 17:11 UTC, MihailsC-hmrc commented on app/audit/models/TaxCalculationDetailsResponseAuditModel.scala
> +  override val detail: JsValue =
Worth to raise with BAs that we don't audit the field `incomeTaxDueAfterOtherCharges` and don't show it on the actual page either.

2021-10-04 09:11 UTC, Wright93 commented on app/audit/models/TaxCalculationDetailsResponseAuditModel.scala
> +    s"${taxBandNameToString(nicBand.name)} (£${nicBand.income} at ${nicBand.rate}%)"
I believe that it covers them all, I went through the messages file to get them

2021-10-04 11:21 UTC, MihailsC-hmrc approved these changes

2021-10-04 11:22 UTC, merged